### ISSUE TITLE
Issue in Insert User Rectangle

### ISSUE THREAD

**Issue by MrMouse2405** [NorthernSantan/Rectangle-Program#1]
There is an issue with the insert user rectangle. The program doesn't stop after accepting the input. <br> <br>
![unknown](https://user-images.githubusercontent.com/68935395/144961062-98dd0b57-2f2d-4ee6-b4d9-115410b7ab7e.png)

**Comment by colin-mccormack** [comment]
I will start on this right away, and will just make commits directly to the main branch.

**Comment by MrMouse2405** [comment]
@NorthernSantan close the issue once it's done.

**Comment by colin-mccormack** [comment]
**Solution** : It turns out this wasn't an issue and simply not well defined behavior. The loop repeats until valid input is entered, but never shows why. This issue was resolved by adding an if with error macro message to alert the user the loop will call again.

![image](https://user-images.githubusercontent.com/80981213/145119934-9d4cb35a-8de4-4d91-b340-1e22162af68f.png)
